# Generated by Django 5.1 on 2024-08-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userscan_userwallet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userscan',
            options={'verbose_name': 'اسکن', 'verbose_name_plural': 'اسکن ها'},
        ),
        migrations.AlterModelOptions(
            name='userwallet',
            options={'verbose_name': 'کیف پول', 'verbose_name_plural': 'کیف پول ها'},
        ),
    ]
