# Generated by Django 5.1 on 2024-08-24 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userscan_options_alter_userwallet_options'),
        ('brand', '0003_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='قیمت در زمان خرید')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brand.asset', verbose_name='asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
