# Generated by Django 5.1 on 2024-08-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_ownedasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscan',
            name='scanned_img',
            field=models.ImageField(blank=True, null=True, upload_to='account/scanned/', verbose_name='تصویر'),
        ),
    ]
