# Generated by Django 5.1 on 2024-09-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userscan_scanned_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='موجودی'),
        ),
    ]
