# Generated by Django 5.1 on 2024-09-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_userwallet_balance'),
        ('brand', '0005_asset_listed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mobile_id', models.CharField(max_length=255, unique=True, verbose_name='آیدی موبایل')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره موبایل')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت')),
                ('rewards', models.ManyToManyField(blank=True, null=True, related_name='ar_assets', to='brand.asset', verbose_name='پاداش ها')),
            ],
        ),
    ]
