# Generated by Django 5.1 on 2024-09-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_aruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aruser',
            name='user_mobile_id',
            field=models.CharField(max_length=255, verbose_name='آیدی موبایل'),
        ),
    ]
