# Generated by Django 5.1 on 2024-08-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand/logo/', verbose_name='لوگو'),
        ),
    ]
