# Generated by Django 5.1 on 2024-08-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد/مقدار/ارزش'),
        ),
    ]
