# Generated by Django 5.1 on 2024-09-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_asset_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='listed',
            field=models.BooleanField(default=False, verbose_name='نمایش در فروشگاه'),
        ),
    ]
